version: "3"

services:
  backend:
    image: strapi/strapi
    depends_on:
      - db
    restart: always
    env_file: .env
    networks:
      - strapi-app-network
    volumes:
      - strapiapp:/srv/app
    ports:
      - "1337:1337"

  db:
    image: postgres:13
    restart: always
    env_file: .env
    networks:
      - strapi-app-network
    volumes:
      - strapidata:/var/lib/postgresql/data

networks:
  strapi-app-network:

volumes:
  strapidata:
    external:
      name: simonyi-web-back_db
  strapiapp:
    external:
      name: simonyi-web-back_app
